################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
FreeRTOS-Plus-IO/Device/tms570ls20x31x/source/tms570ls20x31x_dma.obj: ../FreeRTOS-Plus-IO/Device/tms570ls20x31x/source/tms570ls20x31x_dma.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/source" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS-Plus-IO/Device/tms570ls20x31x/source/tms570ls20x31x_dma.d_raw" --obj_directory="FreeRTOS-Plus-IO/Device/tms570ls20x31x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS-Plus-IO/Device/tms570ls20x31x/source/tms570ls20x31x_driverInterface.obj: ../FreeRTOS-Plus-IO/Device/tms570ls20x31x/source/tms570ls20x31x_driverInterface.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/source" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS-Plus-IO/Device/tms570ls20x31x/source/tms570ls20x31x_driverInterface.d_raw" --obj_directory="FreeRTOS-Plus-IO/Device/tms570ls20x31x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS-Plus-IO/Device/tms570ls20x31x/source/tms570ls20x31x_uart.obj: ../FreeRTOS-Plus-IO/Device/tms570ls20x31x/source/tms570ls20x31x_uart.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/source" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS-Plus-IO/Device/tms570ls20x31x/source/tms570ls20x31x_uart.d_raw" --obj_directory="FreeRTOS-Plus-IO/Device/tms570ls20x31x/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


