################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
FreeRTOS-Plus-FAT/ff_crc.obj: ../FreeRTOS-Plus-FAT/ff_crc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/source" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS-Plus-FAT/ff_crc.d_raw" --obj_directory="FreeRTOS-Plus-FAT" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS-Plus-FAT/ff_dir.obj: ../FreeRTOS-Plus-FAT/ff_dir.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/source" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS-Plus-FAT/ff_dir.d_raw" --obj_directory="FreeRTOS-Plus-FAT" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS-Plus-FAT/ff_error.obj: ../FreeRTOS-Plus-FAT/ff_error.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/source" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS-Plus-FAT/ff_error.d_raw" --obj_directory="FreeRTOS-Plus-FAT" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS-Plus-FAT/ff_fat.obj: ../FreeRTOS-Plus-FAT/ff_fat.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/source" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS-Plus-FAT/ff_fat.d_raw" --obj_directory="FreeRTOS-Plus-FAT" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS-Plus-FAT/ff_file.obj: ../FreeRTOS-Plus-FAT/ff_file.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/source" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS-Plus-FAT/ff_file.d_raw" --obj_directory="FreeRTOS-Plus-FAT" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS-Plus-FAT/ff_format.obj: ../FreeRTOS-Plus-FAT/ff_format.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/source" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS-Plus-FAT/ff_format.d_raw" --obj_directory="FreeRTOS-Plus-FAT" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS-Plus-FAT/ff_ioman.obj: ../FreeRTOS-Plus-FAT/ff_ioman.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/source" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS-Plus-FAT/ff_ioman.d_raw" --obj_directory="FreeRTOS-Plus-FAT" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS-Plus-FAT/ff_locking.obj: ../FreeRTOS-Plus-FAT/ff_locking.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/source" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS-Plus-FAT/ff_locking.d_raw" --obj_directory="FreeRTOS-Plus-FAT" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS-Plus-FAT/ff_memory.obj: ../FreeRTOS-Plus-FAT/ff_memory.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/source" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS-Plus-FAT/ff_memory.d_raw" --obj_directory="FreeRTOS-Plus-FAT" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS-Plus-FAT/ff_stdio.obj: ../FreeRTOS-Plus-FAT/ff_stdio.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/source" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS-Plus-FAT/ff_stdio.d_raw" --obj_directory="FreeRTOS-Plus-FAT" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS-Plus-FAT/ff_string.obj: ../FreeRTOS-Plus-FAT/ff_string.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/source" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS-Plus-FAT/ff_string.d_raw" --obj_directory="FreeRTOS-Plus-FAT" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS-Plus-FAT/ff_sys.obj: ../FreeRTOS-Plus-FAT/ff_sys.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/source" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS-Plus-FAT/ff_sys.d_raw" --obj_directory="FreeRTOS-Plus-FAT" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS-Plus-FAT/ff_time.obj: ../FreeRTOS-Plus-FAT/ff_time.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv7/tools/compiler/ti-cgt-arm_16.9.4.LTS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/source" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="E:/TI/workspace_v7/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --enum_type=packed --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS-Plus-FAT/ff_time.d_raw" --obj_directory="FreeRTOS-Plus-FAT" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


